### ISSUE TITLE
RubyHW1 feedback

### ISSUE THREAD

**Issue by LVALL** [EugeneShitov/RubyHW#1]
Overall looks very good. Seems that you've get the ruby basics pretty well.

According to your comment in task 5:
## Why array[0, -1] not working as you expected ? ##

First of all you're trying to do a slice using -1 index, ruby array doesn't support doing that and returns nil value.

And anyway, the slice reurns an array (e. g.)
```
p array = [15, 0, 12, 2, 17, 3, 0, -18]
p array[0, 2] => [15, 0]
```

your element no way is an array of `[first_element, last_element]`, so condition `(e != array[0, -1])`  is not valid in general (will always return true).

**Comment by EugeneShitov** [comment]
**_Thanks_** a lot for the explanation!
I already clarified this with **Vitaly**,
he explained everything to me,
but I forgot to remove it from the code.
