### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by RoRElessar** [EugeneShitov/RubyHW#2]
Тебе достаточно занести в .gitignore саму директорию `.idea`, не обязательно туда заносить все ее содержимое вручную.

**Comment by EugeneShitov** [comment]
Услышал. 
Вручную не вводил, взял готовое с сайта [gitignore](https://www.toptal.com/developers/gitignore)
Но если это на что-то влияет, открой пожалуйста ещё один issue, я исправлю все свои .gitignore
