### ISSUE TITLE
Фідбек ДЗ 2 1 завдання

### ISSUE THREAD

**Issue by Kashoid23** [EugeneShitov/RubyHW#2]
- [x] Результат вірний, але підберіть більш коректний метод який буде задовілняти умову `– видалити всі непарні числа;`
замість `arr.select(&:even?)`

- [x] Оновіть рішення використавши методи
https://apidock.com/ruby/Array/index
https://apidock.com/ruby/Enumerable/minmax
які дозволять спростити код

`array_res[array_res.each_with_index.min[1]],array_res[array_res.each_with_index.max[1]]=array_res[array_res.each_with_index.max[1]],array_res[array_res.each_with_index.min[1]]`

**Comment by EugeneShitov** [comment]
Перевірте вірність та закрийте питання, якщо все виконав правильно, дякую :)

**Comment by Kashoid23** [comment]
2 пункт ішюс не виконаний

**Оновіть рішення використавши методи**
https://apidock.com/ruby/Array/index
https://apidock.com/ruby/Enumerable/minmax
які дозволять спростити код (це не рішення, а ваш код)

`arr_temp[arr_temp.each_with_index.min[1]], arr_temp[arr_temp.each_with_index.max[1]] = arr_temp[arr_temp.each_with_index.max[1]], arr_temp[arr_temp.each_with_index.min[1]]`

**Comment by EugeneShitov** [comment]
Типу:
```
min_el = arr.index(arr.min)
max_el = arr.index(arr.max)
arr[min_el], arr[max_el] = arr[max_el], arr[min_el]
```
Вірно?
Якщо так - змінив та запушив.

**Comment by Kashoid23** [comment]
Вже краще, але досі не вистачає метода

<img width="947" alt="Screenshot 2022-11-04 at 07 34 08" src="https://user-images.githubusercontent.com/46579145/199897884-c48d2eda-8712-440e-a02f-55c0cd55479d.png">
