### ISSUE TITLE
42 gem feedback

### ISSUE THREAD

**Issue by LVALL** [EugeneShitov/RubyHW#5]
Все зроблено вірно

Just FYI, є можливість зменшити кількість коду, шляхом розширення методів екземпляру в класі Integer напряму

```
# Gem extend Integer class
class Integer
  def forty_two?
    self == 42
  end
end
```
Працюватиме так само. Хоча, якби була необхідність додати більше власних методів, або вони були б складними, ваш підхід в такому випадку був би більш оптимальним.

**Comment by EugeneShitov** [comment]
Окей, мені переробити без модуля?

**Comment by LVALL** [comment]
Ні, не потрібно. Коментарі з приставками NIT, FYI зазвичай просто інформативні. Коли щось потрібно змінити - так і напишемо)
Дякую за швидкий респонз. Можна уже зарезолвити
